version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      js-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: monthly
    groups:
      rust-minor-patch:
        update-types: [minor, patch]
